lib/TransactionValidator.js
lib/utils/SOAPMessageHelper.js
lib/utils/messageWithSchemaValidation.js
test/e2e/authentication.test.js
test/unit/SOAPMessageHelper.test.js
test/unit/messageWithSchemaValidation.test.js

added format again and treat empty objects as self closing tags with the library options
with this changes the files are validated ok with default options and no need to do any modification to the message prior the validation

validate empty complex objects

---

lib/WSDLObject.js
lib/Wsdl11Parser.js
lib/Wsdl20Parser.js
lib/WsdlParserCommon.js
lib/WsdlToPostmanCollectionMapper.js
test/unit/wsdl11Parser.test.js
test/unit/wsdl20Parser.test.js
test/unit/wsdlParserComon.test.js

small improvement I noticed. I believe documentation mentioned in spec under <documentation> is not used currently. Would it be good idea to add it under collection description? (it should be at info.description in collection)
2.1.4 DocumentationWSDL uses the optional wsdl:document element as a container for human readable documentation. The content of the element is arbitrary text and elements ("mixed" in XSD). The documentation element is allowed inside any WSDL language element.
according to spec there is a documentation node in the wsdl under the principal node (description for wsdl 2.0 and definitions for wsdl 1.1)
<description xmlns="http://www.w3.org/ns/wsdl" xmlns:tns="http://www.tmsws.com/wsdl20sample" xmlns:whttp="http://schemas.xmlsoap.org/wsdl/http/"xmlns:wsoap="http://schemas. …

Wsdl documentation to collection desc

---

lib/SchemaPack.js
test/convert-validation/ValidationReport.test.js
test/convert-validation/validateTransactions.test.js
test/unit/SchemaPack.test.js

Currently we have validateTransactions as name of API exposed for validation against schema in wsdl-to-postman.
This should be validateTransaction as defined in openapi module.
Change wsdl-to-postman/lib/SchemaPack.js  validateTransactions(transactions, callback) { to  validateTransaction(transactions, callback) {
change every reference to point the new name.

Fix validateTransactionName

---

lib/TransactionValidator.js
lib/WSDLObject.js
lib/WsdlInformationService11.js
lib/WsdlInformationService20.js
lib/WsdlParser.js
lib/WsdlParserCommon.js
lib/utils/SchemaBuilderXSD.js
lib/utils/messageWithSchemaValidation.js
test/data/validWSDLs11/learnwebservices.wsdl
test/e2e/validateOperationMessagesWithSchema.test.js
test/unit/SchemaBuilderXSD.test.js
test/unit/SchemaPack.test.js
test/unit/WsdlInformationService11.test.js
test/unit/WsdlInformationService20.test.js
test/unit/messageWithSchemaValidation.test.js
test/unit/wsdlParser.test.js
test/unit/wsdlParserComon.test.js

This WSDL is not converted is throwing and error 
http://www.learnwebservices.com/services/hello?WSDL
https://community.postman.com/t/version-8-4-0-import-wsdl-specification/23715
Retrieve all the namespaces definitions form types/schemas, when we are retrieve wsdl elements and the schema is not from the global namespace then search in local namespaces. In validation search for the corresponding namespace definition from global and local before validate message body against schema

Support schema namespace local

---

lib/SchemaPack.js
lib/utils/SOAPHeader.js
lib/utils/WSDLMerger.js
test/unit/WSDLMerger.test.js

Change the use of readFileSync for readFile return a promise in merge functionality for handling asynchronous calls

Avoid use read file sync

---

lib/utils/readInput.js
test/unit/SchemaPack.test.js

issue: after merging converting the file gives this name:
"name": {
"result":false,
"reason":"Invalid input type (folder)....
}
the name should be a string
Instead of creating an error we set to empty string, doing this the name will be taken from the generated (merged) file

Fix incorrect name

---

lib/SchemaPack.js
lib/constants/messageConstants.js
lib/utils/WSDLMerger.js
test/data/separatedFiles/multipleRoot/CountingCategoryData.xsd
test/data/separatedFiles/multipleRoot/CountingCategoryService.wsdl
test/data/separatedFiles/multipleRoot/CountingCategoryServiceCopy.wsdl
test/unit/SchemaPack.test.js
test/unit/TransactionValidator.options.test.js
test/unit/WSDLMerger.test.js

To homologate behavior with OASToPM, when we found more than one root file (service definition) then throw an error via validation result
open api to postman:
this.validationResult = {
result: false,
reason: 'More than one root file not supported.'
};
WSDL to postman:
this.validationResult = {
result: false,
reason: 'There are multiple files with services defined.'
};

Throw error multiple roots

---

lib/SchemaPack.js
lib/TransactionValidator.js
test/data/transactionsValidation/numberToWordsCollectionItemsInvalidXMLBody.json
test/data/transactionsValidation/resultValidation/expectedMissingEndpointaebb36fc.js
test/unit/TransactionValidator.test.js

handle invalid xml input when validate transaction is called
instead of throwing an error we should return empty endpoints for the request and add the not found endpoint in the missingEndpoints array
remove some dead code in TransactionValidator.test.js
added comments on schemapack

Validate transaction invalid xml

---

lib/SchemaPack.js
lib/Validator.js
lib/WSDLObject.js
lib/WsdlParser.js
lib/WsdlParserCommon.js
lib/WsdlToPostmanCollectionMapper.js
test/data/auth/SAMLToken/SenderVouchersOverSSL.wsdl
test/data/auth/usernameToken/NoPassword.wsdl
test/data/auth/usernameToken/NoSecurityBinding.wsdl
test/data/auth/usernameToken/TimeStampNoncePwdHash.wsdl
test/e2e/authentication.test.js
test/e2e/validateOperationMessagesWithSchema.test.js
test/unit/ConversionSpecialCases.test.js
test/unit/SchemaPack.test.js
test/unit/index.test.js
test/unit/validator.test.js
test/unit/wsdlParser.test.js

Parse the document in constructor so we could add the "if only one service take the name of the collection from the name of the service" rule in getMetadata and in convert.
Assign the name if only one service implementation
Also if there is only one folder omit the folder
add the documentation from the service to the folder is there is folder
Modified some security file examples that where incorrect and adequate the test assertions.

Collection name one folder

---

lib/utils/mismatchUtils.js
lib/xsdValidation/LibXMLjs2Facade.js
lib/xsdValidation/LibXMLjsFacade.js
lib/xsdValidation/XMLLintFacade.js
test/unit/TransactionValidator.options.test.js
test/unit/TransactionValidator.test.js
test/unit/mismatchUtils.test.js

- Fix index from xpath when there are multiple siblings with same name in the same level. index based on 1.
- Support to remove the not expected element from the request body in missing in schema errors
- Support to add the missing element to the request body in missing in request errors
- Adding double slash to the generated xpaths

Wrong element substitution in suggestion

---

lib/SchemaPack.js
lib/utils/WSDLMerger.js
lib/utils/readInput.js
test/unit/WSDLMerger.test.js

Using a new optional argument in the input object to determine the input origin and use that to decide which type of path module needs to be used. Use browserified one if input origin is browser.

Changes to support folder inputs on browser and native 

---

lib/TransactionValidator.js
lib/WsdlInformationService11.js
lib/WsdlInformationService20.js
lib/WsdlToPostmanCollectionMapper.js
lib/utils/knownTypes.js
lib/utils/messageWithSchemaValidation.js
test/data/transactionsValidation/wsdlObjects/calculator.js
test/data/transactionsValidation/wsdlObjects/getMatchDetails.js
test/data/transactionsValidation/wsdlObjects/getPlayedMatches.js
test/data/transactionsValidation/wsdlObjects/numberToWords.js
test/data/validWSDLs11/manyfaults.wsdl
test/unit/WsdlInformationService11.test.js
test/unit/messageWithSchemaValidation.test.js
test/unit/wsdlParser.test.js

Add support in conversion and validation for files that have more than one fault in operation
e.g.
<wsdl:operation name=""createPet"">
<wsdl:input message=""tns:createPet"" name=""createPet"">
</wsdl:input>
<wsdl:output message=""tns:createPetResponse"" name=""createPetResponse"">
</wsdl:output>
<wsdl:fault message=""tns:AccessDeniedException"" name=""AccessDeniedException"">
</wsdl:fault>
<wsdl:fault message=""tns:OtherException"" name=""OtherException"">
</wsdl:fault>
</wsdl:operation>
we used to generate only one output and one fault for every request. Due that this file has 2 faults
instead of having one object we have an array, trying to access a property of it returned undefined then the replace operation failed
Now we handle outputs and faults always as an array so if you have one …

Multiple faults

---

lib/TransactionValidator.js
lib/transactionValidator/BodyValidator.js
lib/transactionValidator/HeadersValidator.js
lib/transactionValidator/MethodValidator.js
lib/transactionValidator/QueryParamsValidator.js
test/convert-validation/validateTransactions.test.js
test/unit/TransactionValidator.options.test.js
test/unit/TransactionValidator.test.js
test/unit/transactionValidator/BodyValidator.test.js
test/unit/transactionValidator/HeadersValidator.test.js
test/unit/transactionValidator/MethodValidator.test.js

Separate the transactionValidator into a more semantic classes with single responsibility
added also support for application/soap+xml content type header

Separate validators

---

lib/utils/WSDLMerger.js
lib/utils/readInput.js
package-lock.json
package.json

As we do not use `browserify-fs` for resolution of files for browser environment and use `content` directly. Removing usage of it.
Also with support for `origin` as input while using any API, we will not need to use check like `(process && typeof process.platform === 'string') ? : ` and simple use `this.input.origin` to check running environment.

Removed usage of browserify-fs as it will not be used in browser environment.

---

lib/WSDLParserFactory.js
lib/WsdlInformationService11.js
lib/WsdlInformationService20.js
lib/constants/XSDConstants.js
lib/constants/messageConstants.js
lib/utils/SchemaBuilderXSD.js
lib/utils/WSDLMerger.js
test/data/separatedFiles/noRootFile/Services.wsdl
test/data/separatedFiles/noRootFile/Types.xsd
test/data/separatedFiles/sameTargetnamespace/Services.wsdl
test/data/separatedFiles/sameTargetnamespace/Types.xsd
test/unit/SchemaPack.test.js

Add support for imports with the same target namespace that the WSDL root file, this is an intermediate step to support the include tag (in include tag you have to use the same namespace).
When the imported tag has the same target namespace the types will be added to the root schema.
Added also a correct handling of merging a folder without WSDL root.
Added test scenarios for both cases

Import same namespace

---

lib/WsdlParserCommon.js
lib/utils/WSDLMerger.js
lib/utils/textUtils.js
test/data/separatedFiles/includeTag/Services.wsdl
test/data/separatedFiles/includeTag/Types.xsd
test/unit/SchemaPack.test.js
test/unit/WSDLMerger.test.js
test/unit/wsdlParserCommon.test.js

add support for include tag
change the merge process to read files and preserve the filename.
we now need the name of the file to support include tag (only uses the name for linking)
treat include as an import tag with same namespace
change the way we determine the root file (now can have includes and services not only imports)
Added scenarios for support functions and main scenario

Merging  - Add support for include tag

---

lib/TransactionValidator.js
lib/transactionValidator/HeadersValidator.js
test/convert-validation/validateTransactions.test.js
test/data/transactionsValidation/numberToWordsCollectionItemsCTHeaderNXML.json
test/data/transactionsValidation/numberToWordsCollectionItemsCTHeaderPMVariable.json
test/data/transactionsValidation/numberToWordsCollectionItemsNOSOAPAcHeader.json
test/data/transactionsValidation/numberToWordsCollectionItemsNoCTHeader.json
test/unit/TransactionValidator.test.js
test/unit/transactionValidator/HeadersValidator.test.js

Add SOAPAction header validation while validating transaction.
Options ignore unresolved variables and show missing schema errors.
If the WSDL operation has soapAction then the header must be present and have the same value
If the WSDL operation does not have soapAction then the header must not be present but if the show missing schema errors is true must show the  mismatch as missing in schema
if the value is a PM variable and ignore unresolved variables is true then no mismatch must be present

Validate soap action header

---

lib/WsdlInformationService11.js
lib/WsdlInformationService20.js
lib/WsdlParser.js
lib/WsdlParserCommon.js
lib/utils/SchemaBuilderXSD.js
test/unit/wsdlParser.test.js

This PR fixes issue where if namespace prefix other then `tns` was used, the conversion failed for it. Same is case for `soap` and `http` namespace where we assumed fixed key to be present instead of relying on URL.
https://github.com/postmanlabs/postman-app-support/issues/10067#issuecomment-924106783

Fixed issue where tns was used as fixed name for defining current namespace.

---

lib/WsdlToPostmanCollectionBodyMapper.js
lib/WsdlToPostmanCollectionMapper.js
lib/utils/Cache.js
lib/utils/SOAPMessageHelper.js
lib/utils/XMLMessageHelper.js
lib/utils/textUtils.js
test/data/validWSDLs11/multipleSchemaUsed.wsdl
test/unit/SOAPMessageHelper.test.js
test/unit/cache.test.js
test/unit/textUtils.test.js

Add a cache in body builders
for soap using the root element, protocol and header info to generate a hash (same rules that OAS2Postman)
that hash is going to be the cached element's key.
If the xml message has been previously generated we will return the generated message instead of generating it again.
The cache lives per execution.
Added also cache to xmlMessageHelper for not soap messages

Body builder cache

---

lib/utils/options.js

Reported in https://github.com/postmanlabs/postman-app-support/issues/10513 (endpoing -> endpoint)

Fixed typo in the options description

---

lib/WsdlParserCommon.js
lib/XMLParser.js
lib/utils/textUtils.js
test/unit/textUtils.test.js
test/unit/wsdlParserCommon.test.js

Fixes following issue:
-  No imports were identified for certain kinds of WSDL definition where multiple imports were present under schema with same namespaces.
- XML with certain kinds of comments not being parsed correctly by fast-xml-parser. (Have raised issue [here](https://github.com/NaturalIntelligence/fast-xml-parser/issues/423), but till it's fixed have introduced temporary solution)

Fixed issue where no imports were found for certain kind of WSDL definition.

---

lib/utils/options.js

Fixed issue where `sourceUrl` option was set as an external option even though not supported yet from App.

Updated sourceUrl option to be not set as external.

---

lib/WsdlInformationService11.js
lib/WsdlInformationService20.js
lib/WsdlParser.js
lib/utils/urlUtils.js
test/data/validWSDLs11/addressURIEspecialChars.wsdl
test/data/validWSDLs20/addressURIEspecialChars.wsdl
test/unit/SchemaPack.test.js
test/unit/urlUtils.test.js

Fix html encoded uri
Fixes https://github.com/postmanlabs/postman-app-support/issues/11329
Currently we are not decoding the html uri, so the encodec characters:  &amp; &lt; &gt; &apos;  &quot; are left in the uri
Those characters should be replaced by:  & < > '  " 
Ref:
https://docs.oracle.com/cd/A97335_02/apps.102/bc4j/developing_bc_projects/obcCustomXml.htm
https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML
npm run test
We are replacing the characters once we extract the url and generate the query parameters.
note ![CDATA notation is used only for content and nodes in xml not attributes that is why we are doing the replace in all of  the URIs from address.

Fix html encoded uri

---

lib/WsdlInformationService11.js
lib/utils/XMLParsedUtils.js
test/data/specialCases/NoServicesPortType.wsdl
test/unit/ConversionSpecialCases.test.js
test/unit/WsdlInformationService11.test.js

This PR fixes issues where absence of `portType` in a definition was leading to collection conversion failures on both the Postman App as well as standalone module usage.
Ref: Issue on Postman App Support: https://github.com/postmanlabs/postman-app-support/issues/11267
- Use the wsdl file attached in the github issue mentioned above.
- Try converting it into a postman collection using this module. It should succeed.
- Now try importing the collection's json file on Postman, it should succeed too.

Added handling for specifications with no defined portType

---

lib/utils/SchemaBuilderXSD.js

Improves performance in converting a WSDL file with many types by removing unnecessary deep copying of objects where it is not required.
I profiled the code using [0x](https://www.npmjs.com/package/0x). I've posted a screenshot of the flamegraph below.
In the method [SchemaBuilderXSD.processElementsToWSDElements](https://github.com/postmanlabs/wsdl-to-postman/blob/v1.7.0/lib/utils/SchemaBuilderXSD.js#L661), I found that passing a deep copy of `element` to `getChildren` is unnecessary because:
1. `element` is used in the current function just once to pass it to the `getChildren` method.
2. The variable `elementsFromWSDL` being passed to this method is a local variable in the parent function. Its scope expires when the method completes and is not used anywhere except this method.
So, it is …

Improve performance by removing unnecessary deep copying of objects

---

lib/utils/SchemaBuilderXSD.js
test/unit/SchemaBuilderXSD.test.js

we are having a function named `isLoopReferenceElement` that’s supposed to identify if an element has a reference to itself to avoid a recursion loop.
This function was always accessing `includes()` function on a property called path. As this path was coming from SDK, for certain cases it could be undefined or null. In such cases, this failed with TypeError rather than correct response which should be false for this function.

Fixed issue where conversion failed with typeeror while resolving non defined variables.

---

lib/utils/SchemaBuilderXSD.js
test/data/validWSDLs11/circularComplexTypeReference.wsdl
test/unit/SchemaPack.test.js

This PR fixes the issue where the conversion process was failing with `RageError: Maximum call stack size exceeded`. See added test file in this PR for more detail on the structure of WSDL and to reproduce it
The issue was happening due to an incorrect way of finding out if the element is a looped reference. For this purpose, we are using `isLoopReferenceElement()` method.
This method was finding if current element is already resolved (looped through) once via maintaining resolved references in `lookedReferences` property. And while deciding, then logic was incorrect where it first found the element with same name and then found if the current element `path` contains the found parent element's path.
This logic is incorrect in some cases where `path` which is decided based on parent name …

Fixed issue where circular references were not corectly identified while resolving elements.

---

lib/WsdlInformationService11.js
lib/WsdlInformationService20.js
lib/WsdlParser.js
lib/utils/SOAPBody.js
lib/utils/SchemaBuilderXSD.js
lib/utils/httpUtils.js
test/data/validWSDLs11/noWSDLNamespace.wsdl
test/data/validWSDLs20/noWSDLNamespace.wsdl
test/unit/SOAPBody.test.js
test/unit/WsdlInformationService11.test.js
test/unit/WsdlInformationService20.test.js
test/unit/httpUtils.test.js
test/unit/wsdlParser.test.js

This PR fixes all of known WSDL TypeErrors that are known ATM.
Most of the fixed issues related to TypeErrors were happening because of unsafe access of certain properties.
We'll now be safely accessing such properties and to make sure regression doesn't happen, unit tests for the same are also added.

Fixed all known TypeErrors being caused due to unsafe access of certain properties.

---

lib/WsdlInformationService11.js
lib/WsdlInformationService20.js
lib/WsdlParser.js
test/unit/WsdlInformationService11.test.js
test/unit/WsdlInformationService20.test.js

This PR fixes the issue where for certain valid WSDL, conversion was failing with `Error: Cannot find protocol in those namespaces`.
Issue was happening due to the way we defined binding namespaces. In WSDL definition, one can use bindings like `soap` and `http`. In some cases, there were namespaces defined with such binding twice. Due to this, it could be the case that depending upon the order of these namespace definitions, binding namespaces were not defined correctly while parsing WSDL object.
Function named `getBindingInfoFromBindingTag` in `WsdlParser.js` was using such bindings to define protocol and namespace keys. While doing so in such cases, it was not able to correctly interpret information and detected no binding defined.
We'll now correctly define protocol by going through …

Fixed issue where for multiple binding namespaces conversion was failing.

---

.github/workflows/Test.yml
.github/workflows/draft-new-release.yml
.github/workflows/publish-new-release.yml
Changelog.md
package.json

Automated the Release management process for GitFlow process using steps mentioned in [this blog](https://blog.eizinger.io/12274/using-github-actions-and-gitflow-to-automate-your-release-process).
- Unit tests: Now run on NodeJS versions 12, 16 and 18.
- Bumped up minimum NodeJS version to 12.
- For automation to work the `CHANGELOG.md` file has to match the [Keep A Changelog](https://keepachangelog.com) format. 
- `draft-new-release`: This action is triggered manually. It creates a release branch, bumps up versions in `package.json` and `package-lock.json` and automatically inserts the latest tag in `CHANGELOG.md` file. Then creates PRs against `main` and `development` branches. It requires write access to `contents` and `pull_requests` permissions, which has been done at the job level. …

Releases using GitHub Actions

---

lib/utils/orderSchemasByDependency.js
package-lock.json
test/data/schemaTest/noNamespaceImports.wsdl
test/unit/orderSchemaByDependency.test.js

This PR fixes issue where if WSDL definition had schema imports/includes without no namespace then conversion was failing with error `RangeError: Maximum call stack size exceeded`.
Issue was happening due to improper checking of import elements. We were always expecting import element's namespace but in case not present `toProcess` gets resolved correctly with any namespace without namespace defined as there's no check for `importedName` to be defined.
We'll also start checking that import element name should not be `undefined` while evaluating `toProcess`.

Fixed issue where max stack size was reached while generating collection from certain WSDL definition.

---

lib/security/schemas/inputs/tokens/SAMLTokenInput.js
lib/security/schemas/inputs/tokens/UsernameTokenInput.js
lib/security/schemas/inputs/transport/TransportBindingInput.js
lib/utils/SOAPHeader.js

This PR updates direct consumption of constructor prototype properties. We're now defining class level props of the constructor name instead of direct constructor prototype prop.
Above change is done to make sure that module bundle modification doesn't affect functionality of this module.

Update direct access to constructor prototype props to class props.

---

lib/TransactionValidator.js
lib/WsdlToPostmanCollectionMapper.js
package-lock.json
package.json
test/unit/WsdlToPostmanCollectionMapper.test.js

This PR updates "postman-collection" version used to latest. We're also now making sure that we're only requiring the part of SDK that's used in codebase by requiring specific files.
This means if we use say `Response` from `postman-collection` module then instead of requiring it like below,
```
const { Response } = require('postman-collection');
```
we will be requiring Response from specific module exporting it like below.
```
const { Response } = require('postman-collection/lib/collection/response');
```

Updated "postman-collection" usage to be specific to part of module being used.

---

lib/XMLParser.js
test/unit/XMLParser.test.js

This PR fixes an issue where mergeAndValidate() API throw error for any files in input that contains data not in UTF-8 encoding. Since, for folder import, files can be in such format often time the conversion ended in error.
Issue was with the `fast-xml-parser` module. It throws error while parsing files that are not in UTF-8 format. With this PR, we'll ignore such errors and simply report content of such file as empty string for safeParseToObject() function.
We've also added corresponding tests to make sure intended functionality works as expected.

Fixed an issue where mergeAndValidate() threw error for files not in UTF-8 encoding.

---

lib/WSDLObject.js
lib/WsdlInformationService11.js
lib/WsdlInformationService20.js
lib/WsdlParser.js
lib/WsdlToPostmanCollectionBodyMapper.js
lib/WsdlToPostmanCollectionMapper.js
lib/utils/SOAPMessageHelper.js
test/data/validWSDLs11/elementFormDefaultQualified.wsdl
test/data/validWSDLs11/soapBodyAuthHeaders.wsdl
test/unit/SchemaPack.test.js

- [10466](https://github.com/postmanlabs/postman-app-support/issues/10466) Headers were missing while importing WSDL SOAP collections.
- Input: [AppWSDL.txt](https://github.com/user-attachments/files/17644532/AppWSDL.txt)
- Output -  Headers are present

[10466] Fix for Missing headers in request body
