.github/workflows/Test.yml

Changes on:
.github/workflows/Test.yml
To run all set of tests

changes on github actions

---

assets/xsd2jsonschemafaker.js
lib/TransactionValidator.js
lib/WsdlInformationService11.js
lib/WsdlInformationService20.js
lib/WsdlParserCommon.js
lib/constants/messageConstants.js
lib/security/SecurityAssertionsHelper.js
lib/security/constants/SecurityConstants.js
lib/utils/SOAPHeader.js
lib/utils/SchemaBuilderXSD.js
lib/utils/XMLParsedUtils.js
lib/utils/messageWithSchemaValidation.js
test/unit/SchemaBuilderXSD.test.js
test/unit/SpecialCases.test.js
test/unit/WsdlInformationService11.test.js
test/unit/WsdlInformationService20.test.js
test/unit/XMLParser.test.js
test/unit/messageWithSchemaValidation.test.js
test/unit/wsdlParser.test.js
test/unit/wsdlParserComon.test.js

Fixing Typos for good

---

lib/TransactionValidator.js
package.json

Found these issues while usage of the corresponding API. Let me know if anything is missing.

Fixed typos in implementation of validationPropertiesToIgnore option.

---

index.js
lib/SchemaPack.js
lib/utils/readInput.js
test/unit/readInput.util.test.js

Validate the input in schemapack constructor
change some unit tests

validate input in schemapack constructor

---

.github/workflows/Test.yml
lib/SchemaPack.js
lib/Validator.js
lib/utils/SchemaBuilderXSD.js
lib/utils/XMLParsedUtils.js
lib/utils/getAllTransactions.js
lib/utils/knownTypes.js
lib/utils/messageWithSchemaValidation.js
lib/utils/objectUtils.js
lib/utils/orderSchemaItemsUtils.js
lib/utils/orderSchemasByDependency.js
lib/utils/readInput.js
test/convert-validation/ValidationReport.test.js
test/e2e/indexFunctions.test.js
test/unit/SchemaPack.test.js
test/unit/getAllTransactions.test.js
test/unit/readInput.util.test.js
test/unit/validator.test.js

Fix naming issues, added some comments in methods and extract some constants

names constants and docs

---

lib/utils/WSDLMerger.js
test/unit/WSDLMerger.test.js
test/unit/XMLXSDValidatorFactory.test.js

added tests to some scenarios to increase coverage

Added tests

---

lib/TransactionValidator.js
lib/WsdlToPostmanCollectionMapper.js
test/data/transactionsValidation/numberToWordsCollectionItemsOneMissingItem.json
test/unit/TransactionValidator.test.js

In validation process When there is a missing endpoint and the option is set to    suggestAvailableFixes: true then the suggested value should be the generated request according to the spec. Also the variables should be present

Suggested value missing endpoint

---

assets/xsd2jsonschemafaker.js
test/data/validWSDLs20/Axis2SchemaPositiveInteger.wsdl

added correction for positive integer data type via xsd2json library and add the file with the schema
The library xsd2json is throwing an error processing  <xs:element name="quantity" type="xs:positiveInteger"/> due that is trying to set "exclusiveMaximum": true and should be a number.
Modify the library
generate the schemafaker with browserify
add schemafaker to wsdltopostman
add example file

Added generated schema faker from xsd2json

---

lib/WsdlToPostmanCollectionMapper.js

Change default folder name to be Unnamed Port or Unnamed Service. Changing grammar on Could not get name for folder from ${messageKey} using default instead to Could not get name for folder from ${messageKey}. Using default instead.

Default folder name

---

lib/WsdlInformationService20.js
lib/WsdlToPostmanCollectionMapper.js
test/data/validWSDLs20/heron2.wsdl

Compare operation name only local part of qname
find operation with name in the form ns:OperationName

Failing20 file

---

lib/utils/SchemaBuilderXSD.js
test/unit/SchemaBuilderXSD.test.js

add support for group tag

---

lib/TransactionValidator.js
test/convert-validation/ValidationReport.test.js
test/data/transactionsValidation/calculatorCollectionItemsMissing>.json
test/data/validWSDLs20/2BindingByMessageElement.wsdl
test/data/validWSDLs20/BindingByMessageElement.wsdl
test/data/validWSDLs20/Service1Modified.wsdl
test/data/validWSDLs20/wikipedia.wsdl
test/unit/TransactionValidator.options.test.js

if and endpoint is not found by payload element = operation name neither by soapAction header then try to find it by element name (payload) and operation.input.message

Find endpoint by element name

---

lib/WsdlToPostmanCollectionMapper.js
test/data/validWSDLs20/Service1Modified.wsdl
test/data/validWSDLs20/wikipedia.wsdl
test/unit/ConversionSpecialCases.test.js

filter http operations in mapper

filter http

---

lib/WsdlToPostmanCollectionMapper.js
test/data/schemaTest/importLoop.wsdl
test/unit/orderSchemaByDependency.test.js

Added ut for infinite loop sorting schemas
Removed unused method getBodyMessage  in WsdlToPostmanCollectionMapper.js

Added ut for infinite loop sorting schemas

---

lib/WsdlInformationService11.js
lib/WsdlToPostmanCollectionMapper.js
test/data/validWSDLs11/InnerBindingNOPrefix.wsdl

Support binding with no prefix when trying to find the soap protocol
Assume soap protocol when there is no prefix in binding tag
Added soap action header in original request for responses

Issue can not find protocol in those namespaces

---

lib/utils/ElementResolver.js
lib/utils/SchemaBuilderXSD.js
lib/utils/objectUtils.js
package-lock.json
package.json
test/unit/SchemaBuilderXSD.test.js

Issue 13:
Issue link:
https://github.com/postmanlabs/postman-app-support/issues/10298
https://github.com/postmanlabs/postman-app-support/issues/10251
Slack thread
https://wizeline.slack.com/archives/C01JNAG512P/p1632152267001800
1. Problem description / What is the issue?
While importing the user receives a message saying “Converting circular structure to JSON.”
2. Root cause analysis / What caused the issue?
This happened because the file has circular references. And the error is sent by the JSON.parse(JSON.stringify(foundElement)); instruction
3. fix we implemented / What is the resolution?
First of all instead of cloning the object with JSON.parse(JSON.stringify(foundElement)); Now we use clone library https://www.npmjs.com/package/clone
Second, if an infinite loop is found then we …

Change deep cloning

---

test/data/separatedFiles/remoteRefs/remoteStockquote.wsdl
test/data/separatedFiles/remoteRefs/remoteStockquote.xsd
test/data/separatedFiles/remoteRefs/remoteStockquoteservice.wsdl

using development branch as a repository for remote references files

Added remote files as blob

---

assets/xsd2jsonschemafaker.js
lib/constants/XSDConstants.js
lib/utils/SchemaBuilderXSD.js
test/data/schemaTest/attributeIssue.wsdl
test/data/validWSDLs11/attributeIssue.wsdl
test/unit/SchemaBuilderXSD.test.js
test/unit/SchemaPack.test.js

- Adding support to global attributes 
- Adding support to 'fixed' property in global attributes
- xsd2jsonschemafaker fixed to support fixed property in parsing

Global attributtes not supported issue

---

test/data/separatedFiles/remoteRefsServiceFinderQuery/ServiceFinderQuery.wsdl
test/data/separatedFiles/remoteRefsServiceFinderQuery/xsd0.xsd
test/data/separatedFiles/remoteRefsServiceFinderQuery/xsd1.xsd
test/data/separatedFiles/remoteRefsServiceFinderQuery/xsd2.xsd
test/data/separatedFiles/remoteRefsServiceFinderQuery/xsd3.xsd

added files to blob for remote refs

Added files to blob for remote refs

---

assets/xsd2jsonschemafaker.js
lib/WsdlParserCommon.js
lib/XMLParser.js
lib/utils/textUtils.js
lib/xsdValidation/LibXMLjs2Facade.js
lib/xsdValidation/LibXMLjsFacade.js
lib/xsdValidation/XMLLintFacade.js
test/unit/XMLXSDValidator.test.js
test/unit/textUtils.test.js
test/unit/wsdlParserCommon.test.js

Fixes issue https://github.com/postmanlabs/postman-app-support/issues/10484.

Fixed issue where anySimpleType and anyAtomicType data types caused collection generation failure.

---

Changelog.md
package-lock.json
package.json

- Stable release
- Removed libxmljs
- Added changelog

Release v1.1.0

---

lib/utils/SchemaBuilderXSD.js
package-lock.json
test/data/validWSDLs11/schemaExternalNS.wsdl

Messages not constructed correctly
The xsd2json library is throwing an error because it cannot find the xsd1 namespace
Add an externally defined namespace (in root) used in the schema into the schema so the xsd2json process does not throw an error.
https://github.com/postmanlabs/postman-app-support/issues/10818

Add ext ns to schema

---

lib/SchemaPack.js
lib/bundleFiles.js
lib/utils/WSDLMerger.js
test/unit/SchemaPack.test.js
test/unit/bundleFiles.test.js

Fix issue selecting roots when they are explicit
Re arrange tests, from index to bundleFiles
Fix errors while taking roots when are present in the input array
- npm run test

Fix issue with roots

---

lib/utils/orderSchemasByDependency.js
test/data/schemaTest/importDeepLoop.wsdl
test/unit/orderSchemaByDependency.test.js

While trying to sort the schemas by dependency there is a case when the schemas have imports that lead to an infinite loop:
```
<xsd:schema elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.xsd2jsonschema.org/example">
<xsd:import namespace="http://www.xsd2jsonschema.org/example2"/>
<xsd:import namespace="http://www.xsd2jsonschema.org/example3"/>
</xsd:schema>
<xsd:schema elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.xsd2jsonschema.org/example2">
<xsd:import namespace="http://www.xsd2jsonschema.org/example"/>
<xsd:import namespace="http://www.xsd2jsonschema.org/example3"/>
</xsd:schema>
<xsd:schema elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" …
```

schemas loop reference

---

test/data/separatedFiles/remoteDeepCircularRef/ServiceFinderQuery.wsdl
test/data/separatedFiles/remoteDeepCircularRef/xsd0.xsd
test/data/separatedFiles/remoteDeepCircularRef/xsd1.xsd
test/data/separatedFiles/remoteDeepCircularRef/xsd2.xsd
test/data/separatedFiles/remoteDeepCircularRef/xsd3.xsd

Adding test files to create test scenario remoteDeepCircularRefs

Remote files

---

package-lock.json
package.json

Upgraded libxmljs2 to from 0.27.0 to 0.30.1 to support node 18

Upgraded libxmljs2 from 0.27.0 to 0.30.1

---

CHANGELOG.md

Adds missing changelogs for release v1.10.0.

Added changelogs for release v1.10.0.

---

lib/utils/URLEncodedParamsHelper.js
lib/utils/XMLParsedUtils.js
test/unit/URLEncodedParamsHelper.test.js

Ensuring type of arguments are correct and not null or undefined.

Ensuring correct type of parameter before using

---

lib/TransactionValidator.js
lib/XMLParser.js
package-lock.json
package.json
test/unit/SchemaBuilderXSD.test.js
test/unit/SchemaPack.test.js
test/unit/SecurityAssertionsHelper.test.js
test/unit/XMLParser.test.js
test/unit/cliTool.test.js
test/unit/validator.test.js
test/unit/wsdlParser.test.js
test/unit/wsdlParserCommon.test.js

This PR makes WSDL validate() check stricter by also validating that XML validity is also checked to avoid typeerrors further down the line while conversion.
We had various issues in test files where XMLs were invalid so with this PR, I've also fixed them.

Fixed issue where invalid XMLs were reported as valid WSDLs.

---

lib/security/SecurityAssertionsHelper.js
lib/utils/SchemaBuilderXSD.js
lib/utils/knownTypes.js

Fixing these errors:-
https://postmanlabs.atlassian.net/browse/IMPORT-1190
https://postmanlabs.atlassian.net/browse/IMPORT-1141
https://postmanlabs.atlassian.net/browse/IMPORT-1114
https://postmanlabs.atlassian.net/browse/IMPORT-1072

Fixing various type, null, undefined errors

---

.github/workflows/Test.yml
.gitignore
lib/WsdlInformationService11.js
lib/WsdlInformationService20.js
lib/WsdlParserCommon.js
lib/utils/SOAPBody.js
package-lock.json
package.json
test/unit/WsdlInformationService11.test.js
test/unit/wsdlParserCommon.test.js

This PR fixes incorrect reporting of errors. We've made changes so that reported UserErrors by child function will get reported as such instead of WsdlError.
We've also made changes to keep minimum supported node version from v12 to now v16.

Fixed issue where UserErrors were reported as conversion errors.
